// src/App.tsx
import { useEffect } from 'react'
import { KLineChartPro } from '@klinecharts/pro'
import '@klinecharts/pro/dist/klinecharts-pro.css'
import './App.css'
import { CoinrayDatafeed } from './CoinrayDatafeed'

function App() {
  let initialized = false;

  useEffect(() => {
    if ((import.meta.env.VITE_APP_ENV || 'development') as string === 'development') {
      console.log("Running in development mode")
      if (!initialized) {
        initialized = true;
        return;
      }
    }
    const chart = new KLineChartPro({
      container: document.getElementById('chart-container') || '',
      symbol: {
        exchange: 'BINA',
        market: 'crypto',
        name: 'United States Dollar Tether vs Bitcoin',
        shortName: 'USDT_BTC',
        ticker: 'USDT_BTC',
        priceCurrency: 'usd',
        type: 'ADRC',
      },
      period: { multiplier: 1, timespan: 'minute', text: '1m' },
      datafeed: new CoinrayDatafeed(),
    })

    const handleResize = () => chart.resize()
    window.addEventListener('resize', handleResize)
    return () => {
      window.removeEventListener('resize', handleResize)
      // chart?.dispose()
    }
  }, [])

  return <div className="chart-ui" id="chart-container"></div>
}

export default App

// src/App.vue
<script setup lang="ts">
import { onMounted } from 'vue'
import { KLineChartPro, DefaultDatafeed } from '@klinecharts/pro'
import '@klinecharts/pro/dist/klinecharts-pro.css'
import Coinray, { CoinrayCache } from 'coinrayjs'
import { CoinrayDatafeed } from './CoinrayDatafeed'

onMounted(() => {
  const chart = new KLineChartPro({
    container: document.getElementById('container') || '',
    // Default symbol info
    symbol: {
      exchange: 'BINA',
      market: 'crypto',
      name: 'United States Dollar Tether vs Bitcoin',
      shortName: 'USDT_BTC',
      ticker: 'USDT_BTC',
      priceCurrency: 'usd',
      type: 'ADRC',
    },
    // Default period
    period: { multiplier: 1, timespan: 'minute', text: '1m' },
    // The default data access is used here. If the default data is also used in actual use, you need to go to the https://polygon.io/ apply for API key
    datafeed: new CoinrayDatafeed(),
  })
  window.addEventListener('resize', () => {
    //TODO: Resize chart
  })
})
</script>

<template>
  <div style="height: 100vh; width: 100vw;" id="container"></div>
</template>

<style scoped>
</style>
